import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import NextTopLoader from 'nextjs-toploader';
import { SessionProvider } from "next-auth/react"
import { Toaster } from "sonner";

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/providers/theme-provider";
import { QueryProvider } from "@/providers/query-provider";
import { ModalProvider } from "@/providers/modal-provider";
import { auth } from "@/auth";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "Basic Education Care",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
            <QueryProvider>
              {children}
              <Toaster />
              <ModalProvider />
              <NextTopLoader showSpinner={false} />
            </QueryProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
